name: computer_vision
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=22.1.2
  - pip:
    - ipykernel
    - matplotlib==3.6
    - pandas==1.5
    - facenet_pytorch
    - tqdm
    - pytorch-lightning
    - opencv-python